### PR TITLE
es 2015 and an onscroll event handler

### PR DESCRIPTION
**Pull request by jes5e**
The motivation for this set of changes was the need to  be able to pass in a handler to listen for scroll events. In doing so I also made some updates to fix React warnings that have come up with more recent React versions, and additionally updated it to use es 2015.

### CODE REVIEW

**Comment by gimdongwoo** [comment]
Thank you very much for your great PR.
I sincerely apologize for the delay in responding.

The ES6 version of code is maintained in the following repository:
Https://github.com/gimdongwoo/react-chatview-es6

And, the onScroll Handler is implemented in the previously submitted PR with the name 'returnScrollable'.
https://github.com/gimdongwoo/react-chatview-es6#documentation
I think 'returnScrollable' is for flexible ways.

**Comment by jes5e** [comment]
Hi Dongwoo, thanks for the update. Just curious why there is now a separate
github project for the update to es6? Is react-chatview "non es6" no longer
being maintained?

Thanks a lot,

Jesse

On Jul 12, 2017 2:08 AM, "Dongwoo Gim" <notifications@github.com> wrote:

Closed #24 <https://github.com/dustingetz/react-chatview/pull/24>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dustingetz/react-chatview/pull/24#event-1160085135>,
or mute
the thread

**Comment by gimdongwoo** [comment]
The project has been merged.

The original react-chatview owner did not want to upgrade to es6 in the past.

That's why I'm using the es6 version of the code separately.

Your work is great. Thank you!

**Comment by dustingetz** [comment]
I transfered ownership to gimdongwoo, dustingetz/react-chatview is now jsdevkr/react-chatview with a redirect, is that the source of confusion?

**Comment by jes5e** [comment]
Thanks for the reply. Yes, that is the source of my confusion. It seems
like there are now two divergent projects. When I Google react chat view it
takes me to github/jsdevkr/react-chatview.  Is github somehow doing a
redirect to dustingetz/react-chatview-es6?

Also, thanks so much for building this in the first place! It's a really
great project and does exactly what I need and saved me a ton of time.



On Jul 21, 2017 9:11 AM, "Dustin Getz" <notifications@github.com> wrote:

I transfered ownership to gimdongwoo, dustingetz/react-chatview is now
jsdevkr/react-chatview with a redirect, is that the source of confusion?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jsdevkr/react-chatview/pull/24#issuecomment-316996880>,
or mute the thread

**Comment by dustingetz** [comment]
Sure no problem. To clear things up,
`jsdevkr/react-chatview` is head, `dustingetz/react-chatview` redirects to head
`gimdongwoo/react-chatview-es6` is even with `jsdevkr/react-chatview`, the es6 changes are merged
`dustingetz/react-chatview-es6` isn't a thing

**Comment by gimdongwoo** [comment]
Yes. @dustingetz 's comment is perfect.

`gimdongwoo/react-chatview-es6` is just fork repository of `jsdevkr/react-chatview` now.

And we will handle to the issues needed for the `react-chatview 0.1.x` version corresponding to [`react 14` branch](https://github.com/jsdevkr/react-chatview/tree/react14).

**Pull request closed without merging**
