### PR TITLE
fix issue when element is removed from list

### PR DESCRIPTION
**Pull request by adam187**
fix issue when element is removed from list and scroll is not in same place as before

### CODE REVIEW

**Comment by dustingetz** [comment]
Hi Adam. Thank you for the excellent PR with comments. I forked the jsfiddle on the readme to try to reproduce the issue: https://jsfiddle.net/dustingetz/h9hvsdx5/ does this fiddle demonstrate the issue and what exactly is the desired behavior?

**Comment by adam187** [comment]
Hi @dustingetz, Yes this jsfiddle demonstrate issue that i experienced.  

So for example when i have scroll bar position set so message `14` is at the bottom of a list, and i remove some message from a list, then message `14` is no longer at the bottom of a list, and you need to scroll down to see message `14` again. This is probably not a big deal. 

In my particular use case bigger issue was removing message from beginning of a list when new message wa added, or adding new message at beginning of a list when message was removed. 
My application display fixed number of messages. For example `20`, `40`, `60` (It depends how far user scrolls). So when user post new message, old message from beginning(top) of a list is being removed, and when user remove message, it adds message back at beginning (top) of a list.

**Comment by dustingetz** [comment]
Thanks, I understand the issue now. Your changeset looks good but I need to put together a more thorough test case to be sure. I'll get back to you.

**Comment by dustingetz** [comment]
Hi Adam, I landed this PR, but I don't think the issue is fully resolved. See this fiddle which contains your patch: https://jsfiddle.net/dustingetz/h9hvsdx5/

The issue is solved for the first row deleted, but if you delete another row the issue comes back. Am I mis understanding?

**Comment by adam187** [comment]
Hi @dustingetz, i finally found some time to check out you response.

Looks to me that my change is missing in build that you used in this example.

Example with my build works as expected:
[https://jsfiddle.net/adam187/qy81k5dc/1/]()

Looks like you used some old build from 11 Jan 2016  https://github.com/dustingetz/react-chatview/tree/184094e84eab3e6862bd25d5686d41736a81e09a

Event your latest build on master don't have my changes in dist file.

this changes:
https://github.com/dustingetz/react-chatview/blob/master/src/react-chatview.js#L146-L152

should be here:
https://github.com/dustingetz/react-chatview/blob/master/dist/react-chatview.js#L203

**Pull request merged**
